# Variaveis secretas a serem definidas
#
# environment: nome-da-main-env
# GCP_PROJECT_ID: nome-do-id-projeto-gcp
# GCP_CREDENTIALS: chaves IAM credenciais
#
# Variaveis a serem definidas
#
# NAME_PROJECT: "nome-do-projeto" <<< defina o nome do projeto  >>>
# DOC_REPOSITORY: "nome-do-repositorio/" <<< defina o nome do repositorio  >>>
# LOCATIONS: "us-central1" <<< defina a região da maquina e arquivos  >>>
# MIN_INSTANCE: 0 <<< defina a quantidade de instancias minimas>>>
# MAX_INSTANCE: 1 <<< defina a quantidade de instancias maximas>>>
# MEMORY_RAM: '128Mi' <<<< defina a quantidade de memoria ram da VM>>>>
#
#
# não altere
# IMAGE_NAME: "-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/"
#
# Nome da Action
name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    # defina a secret ENVs
    environment: nextProjectEnvs
    # defina a ENVs
    env:
      # defina o nome do projeto
      NAME_PROJECT: 'nova-agil'
      # defina o nome do repositorio existente
      DOC_REPOSITORY: "tes/"
      # defina a região
      LOCATIONS: "us-central1"
      # defina a instancia minima
      MIN_INSTANCE: 0
      # defina a instancia maxima
      MAX_INSTANCE: 1
      # defina a quantidaded e memoria ram para vm
      MEMORY_RAM: "128Mi"
      # não altere
      IMAGE_NAME: "-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # etapa autenticação
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # criando a imagem
      - name: Build Docker image
        run: docker build -t $LOCATIONS$IMAGE_NAME$DOC_REPOSITORY$NAME_PROJECT .

      # levantando a imagem para server Artifact Registry
      - name: Tag and Push Docker image to Artifact Registry
        run: docker push $LOCATIONS$IMAGE_NAME$DOC_REPOSITORY$NAME_PROJECT

      # exectando o deploy da imagem no servidor
      - name: Deploy Docker image to Cloud Run
        run: gcloud run deploy $NAME_PROJECT --image $LOCATIONS$IMAGE_NAME$DOC_REPOSITORY$NAME_PROJECT --region $LOCATIONS --memory $MEMORY_RAM --min-instances $MIN_INSTANCE --max-instances $MAX_INSTANCE --platform managed --port 80 --allow-unauthenticated
